# Generated by Django 5.0.4 on 2024-08-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='customer_contact',
            new_name='customer_contact_india',
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_contact_other',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
