# Generated by Django 5.0.4 on 2024-08-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_customer_contact_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price_aed',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_inr',
        ),
    ]
